#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Wed Oct 10 18:01:21 2007

import wx
import kabenc

class EncShowFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: EncShowFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.txt_enc = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        self.Bind(wx.EVT_CLOSE, self.OnClose)

    def __set_properties(self):
        # begin wxGlade: EncShowFrame.__set_properties
        self.SetTitle("Encrypted HTML output")
        self.SetSize((921, 741))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: EncShowFrame.__do_layout
        sizer_3 = wx.GridSizer(1, 1, 0, 0)
        sizer_3.Add(self.txt_enc, 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_3)
        self.Layout()
        # end wxGlade

    def OnClose(self, event):
        print "enc frame closing"
        self.Hide()
        # no .skip...???

# end of class EncShowFrame


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.lbl_uri = wx.StaticText(self, -1, "Enter Uri")
        self.txt_uri = wx.TextCtrl(self, -1, "http://finance.yahoo.com")
        self.lbl_password = wx.StaticText(self, -1, "Enter password (hex)")
        self.txt_password = wx.TextCtrl(self, -1, "DEADFACE123123123123123400000000", style=wx.TE_PASSWORD)
        self.chk_embed = wx.CheckBox(self, -1, "Embed script?")
        self.static_line_1 = wx.StaticLine(self, -1)
        self.btn_ok = wx.Button(self, -1, "Encrypt")
        self.btn_cancel = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.encryptClicked, self.btn_ok)
        self.Bind(wx.EVT_BUTTON, self.cancelClicked, self.btn_cancel)
        # end wxGlade
        
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.encFrame = EncShowFrame(None, -1, "")

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Kill adblock demo")
        self.txt_uri.SetMinSize((400, 28))
        self.txt_uri.SetFocus()
        self.lbl_password.SetToolTipString("Example: 00DEAD00FACE00")
        self.txt_password.SetMinSize((400, 28))
        self.btn_ok.SetBackgroundColour(wx.Colour(35, 142, 35))
        self.btn_cancel.SetBackgroundColour(wx.Colour(255, 0, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_1.Add(self.lbl_uri, 0, wx.ALL, 0)
        grid_sizer_1.Add(self.txt_uri, 0, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.lbl_password, 0, wx.ALL, 0)
        grid_sizer_1.Add(self.txt_password, 0, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL|wx.EXPAND, 0)
        sizer_1.Add(self.chk_embed, 0, wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_1.Add((249, 50), 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.btn_ok, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.btn_cancel, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(sizer_2, 1, 0, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def encryptClicked(self, event): # wxGlade: MyDialog.<event_handler>
        print "Event handler `encryptClicked'"
        encText = kabenc.encrypt(self.txt_uri.GetValue(), self.txt_password.GetValue())
        #print dir(self.encFrame.txt_enc)
        self.encFrame.txt_enc.Clear()
        self.encFrame.txt_enc.WriteText(encText)
        print encText
        self.encFrame.Show()
        
        event.Skip()

    def cancelClicked(self, event): # wxGlade: MyDialog.<event_handler>
        print "Event handler `cancelClicked'"
        self.Close()
        event.Skip()

    def OnClose(self, event):
        dial = wx.MessageDialog(None, 'Are you sure to quit?', 'Question',
            wx.YES_NO | wx.YES_DEFAULT | wx.ICON_QUESTION)
        ret = dial.ShowModal()
        if ret == wx.ID_YES:
            del self.encFrame
            self.Destroy()
        else:
            event.Veto()
            
# end of class MyDialog


class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        dialog_1 = MyDialog(None, -1, "")
        self.SetTopWindow(dialog_1)
        dialog_1.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
