#!/usr/bin/python
import sys,os

if len(sys.argv) > 1:
	os.system("uisp -dapa -dno-poll -dlpt=3 --erase")
	os.system("uisp -dapa -dno-poll -dlpt=3 --upload if=%s" % sys.argv[1])
	os.system("uisp -dapa -dno-poll -dlpt=3 --verify if=%s" % sys.argv[1])
else:
	print "Usage %s file.srec" % sys.argv[0]

